name: Filmogenic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13024
title: Are you filmogenic?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#42aef9'
    - '#000002'
    - '#cccbcf'
    - '#36353a'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0
purpose: []
