name: Filmogenic
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Are you readY?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#42aef9'
    - '#000002'
    - '#cccbcf'
    - '#36353a'
  brandStrength: 0.8890468198806047
  lightness: 0.3601207009050995
  saturation: 0.3346275808289647
  rhythmicContrast: 0.31812726240605116
purpose: []
