name: Filmogenic
favicon: null
layout_spectrum: 0.2845625407062471
typography_spectrum: 0.7355372777674347
title: Are you readY?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040406'
    - '#d6dcdc'
    - '#23408a'
    - '#8e0007'
    - '#887d67'
  brandStrength: 0.8890468198806047
  lightness: 0.3601207009050995
  saturation: 0.3346275808289647
  rhythmicContrast: 0.31812726240605116
purpose: []
